"""create discussion topic and response tables

Revision ID: 5aa60b410b0b
Revises: 31ec138cf77b
Create Date: 2023-10-09 17:47:07.293683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aa60b410b0b'
down_revision = '31ec138cf77b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discussion_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('discussion_topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discussion_topic_id'], ['discussion_topics.id'], name=op.f('fk_discussion_responses_discussion_topic_id_discussion_topics')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_discussion_responses_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_todolist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_todolist',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('todo_list', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['todo_list'], ['todo_lists.id'], name='fk_user_todolist_todo_list_todo_lists'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_todolist_user_id_users')
    )
    op.drop_table('discussion_responses')
    op.drop_table('discussion_topics')
    # ### end Alembic commands ###
