"""create meeting question table

Revision ID: f61b64e8fa66
Revises: 74ecf64967bd
Create Date: 2023-10-07 10:31:46.413299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f61b64e8fa66'
down_revision = '74ecf64967bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standup_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_question',
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('standup_question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], name=op.f('fk_meeting_question_meeting_id_meetings')),
    sa.ForeignKeyConstraint(['standup_question_id'], ['standup_questions.id'], name=op.f('fk_meeting_question_standup_question_id_standup_questions'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_question')
    op.drop_table('standup_questions')
    # ### end Alembic commands ###
